Importing Libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Importing Data and Reading

In [6]:
df = pd.read_excel('road_accident_data.xlsx')
df

,ID,State,Date,Day_of_Week,Time_of_Day,Weather_Conditions,Road_Conditions,Light_Conditions,Type_of_Road,Type_of_Junction,...,Num_Vehicles_Involved,Num_Casualties,Speed_Limit,Distance_to_Nearest_Hospital,Distance_to_Nearest_Police_Station,Visibility,Road_Width,Road_Surface_Friction_Coefficient,Vehicle_Speed,Time_Taken_for_Emergency_Response
0,165433,Connecticut,2024-02-20 05:46:20,Tuesday,19:59:02,Rainy,Muddy,Daylight,Street,T-Junction,...,2,3,57.0,3.303606,3.139351,485.649012,4.886202,0.904971,45.0,25.152781
1,165434,Massachusetts,2024-01-09 05:08:31,Wednesday,21:28:51,Sunny,Muddy,Daylight,Highway,Intersection,...,1,0,55.0,2.715327,3.634593,616.979936,4.677592,0.949236,41.0,23.163817
2,165435,Wyoming,2024-02-20 08:26:27,Thursday,18:04:26,Snowy,Snowy,Dawn,Street,Underpass,...,3,1,38.0,4.811429,9.631561,838.741654,9.926058,0.184447,64.0,6.697750
3,165436,Hawaii,2024-01-15 03:23:47,Sunday,16:51:02,Snowy,Icy,Daylight,Street,Intersection,...,5,0,59.0,6.976968,2.334468,842.441019,4.351822,0.195811,NaN,6.595036
4,165437,Oklahoma,2024-02-10 10:17:29,Tuesday,14:19:19,Foggy,Icy,Night,Rural,T-Junction,...,2,0,53.0,3.724599,4.359620,905.620263,6.626862,0.954821,81.0,22.913128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1605,167038,New Jersey,2024-01-16 08:39:47,Monday,05:40:02,Sunny,Snowy,Dusk,Rural,Overpass,...,3,0,NaN,5.526823,0.462281,313.519646,8.653699,0.814166,29.0,NaN
1606,167039,Wyoming,2024-01-24 21:39:23,Sunday,00:54:20,Rainy,Wet,Dawn,Freeway,Roundabout,...,4,0,37.0,0.794841,2.881738,657.264720,8.388508,0.311292,12.0,13.507650
1607,167040,New Mexico,2024-02-03 17:53:45,Sunday,19:15:52,Stormy,Wet,Dusk,Rural,Crossroads,...,2,2,70.0,6.716450,3.630358,590.511805,8.197109,0.469393,51.0,13.239562
1608,167041,Oklahoma,2024-01-25 18:16:24,Monday,02:12:24,NaN,Wet,Night,Freeway,Roundabout,...,1,0,31.0,8.396440,7.895523,492.994027,3.017950,0.397886,31.0,13.939866
1609,167042,Maryland,2024-01-24 02:29:38,Sunday,15:04:42,Stormy,Muddy,Dusk,Street,Roundabout,...,5,2,67.0,2.292247,4.886780,266.434309,6.440846,0.343519,76.0,12.826442

Explore and Look the Data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1610 entries, 0 to 1609
Data columns (total 23 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  1610 non-null   int64
 1   State                               1610 non-null   object
 2   Date                                1610 non-null   datetime64[ns]
 3   Day_of_Week                         1610 non-null   object
 4   Time_of_Day                         1610 non-null   object
 5   Weather_Conditions                  1461 non-null   object
 6   Road_Conditions                     1610 non-null   object
 7   Light_Conditions                    1610 non-null   object
 8   Type_of_Road                        1610 non-null   object
 9   Type_of_Junction                    1455 non-null   object
 10  Type_of_Accident                    1610 non-null   object
 11  Vehicle_Type                        1610 non-null   object
 12  Driver_Age_Group                    1610 non-null   object
 13  Num_Vehicles_Involved               1610 non-null   int64
 14  Num_Casualties                      1610 non-null   int64
 15  Speed_Limit                         1457 non-null   float64
 16  Distance_to_Nearest_Hospital        1610 non-null   float64
 17  Distance_to_Nearest_Police_Station  1610 non-null   float64
 18  Visibility                          1610 non-null   float64
 19  Road_Width                          1453 non-null   float64
 20  Road_Surface_Friction_Coefficient   1610 non-null   float64
 21  Vehicle_Speed                       1433 non-null   float64
 22  Time_Taken_for_Emergency_Response   1444 non-null   float64
dtypes: datetime64[ns](1), float64(8), int64(3), object(11)
memory usage: 289.4+ KB

In [ ]:
df.dtypes

ID                                             int64
State                                         object
Date                                  datetime64[ns]
Day_of_Week                                   object
Time_of_Day                                   object
Weather_Conditions                            object
Road_Conditions                               object
Light_Conditions                              object
Type_of_Road                                  object
Type_of_Junction                              object
Type_of_Accident                              object
Vehicle_Type                                  object
Driver_Age_Group                              object
Num_Vehicles_Involved                          int64
Num_Casualties                                 int64
Speed_Limit                                  float64
Distance_to_Nearest_Hospital                 float64
Distance_to_Nearest_Police_Station           float64
Visibility                                   float64
Road_Width                                   float64
Road_Surface_Friction_Coefficient            float64
Vehicle_Speed                                float64
Time_Taken_for_Emergency_Response            float64
dtype: object

In [ ]:
df.describe().round()

,ID,Date,Num_Vehicles_Involved,Num_Casualties,Speed_Limit,Distance_to_Nearest_Hospital,Distance_to_Nearest_Police_Station,Visibility,Road_Width,Road_Surface_Friction_Coefficient,Vehicle_Speed,Time_Taken_for_Emergency_Response
count,1610.0,1610,1610.0,1610.0,1457.0,1610.0,1610.0,1610.0,1453.0,1610.0,1433.0,1444.0
mean,166238.0,2024-01-30 19:29:33.383229440,3.0,1.0,50.0,5.0,5.0,554.0,7.0,1.0,50.0,18.0
min,165433.0,2024-01-01 00:44:44,1.0,0.0,30.0,0.0,0.0,100.0,3.0,0.0,0.0,5.0
25%,165835.0,2024-01-15 22:21:01.249999872,2.0,0.0,40.0,3.0,3.0,328.0,5.0,0.0,24.0,12.0
50%,166238.0,2024-01-30 18:24:35.500000,3.0,1.0,50.0,5.0,5.0,557.0,7.0,1.0,49.0,17.0
75%,166640.0,2024-02-14 17:17:31,4.0,3.0,60.0,8.0,7.0,782.0,8.0,1.0,76.0,24.0
max,167042.0,2024-02-29 01:31:24,5.0,3.0,70.0,10.0,10.0,1000.0,10.0,1.0,100.0,30.0
std,465.0,NaN,1.0,1.0,12.0,3.0,3.0,259.0,2.0,0.0,29.0,7.0

Check Coulmn Data type

In [ ]:
df['Time_of_Day'] = pd.to_datetime(df['Time_of_Day'], errors = 'coerce')

C:\Users\DELL\AppData\Local\Temp\ipykernel_5552\3705327844.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Time_of_Day'] = pd.to_datetime(df['Time_of_Day'], errors = 'coerce')

In [ ]:
df.dtypes

ID                                             int64
State                                         object
Date                                  datetime64[ns]
Day_of_Week                                   object
Time_of_Day                           datetime64[ns]
Weather_Conditions                            object
Road_Conditions                               object
Light_Conditions                              object
Type_of_Road                                  object
Type_of_Junction                              object
Type_of_Accident                              object
Vehicle_Type                                  object
Driver_Age_Group                              object
Num_Vehicles_Involved                          int64
Num_Casualties                                 int64
Speed_Limit                                  float64
Distance_to_Nearest_Hospital                 float64
Distance_to_Nearest_Police_Station           float64
Visibility                                   float64
Road_Width                                   float64
Road_Surface_Friction_Coefficient            float64
Vehicle_Speed                                float64
Time_Taken_for_Emergency_Response            float64
dtype: object

Data Cleaning

Duplicated

In [ ]:
df.duplicated().sum()

np.int64(0)

NaNs Values

In [ ]:
df.isnull().sum()

ID                                      0
State                                   0
Date                                    0
Day_of_Week                             0
Time_of_Day                             0
Weather_Conditions                    149
Road_Conditions                         0
Light_Conditions                        0
Type_of_Road                            0
Type_of_Junction                      155
Type_of_Accident                        0
Vehicle_Type                            0
Driver_Age_Group                        0
Num_Vehicles_Involved                   0
Num_Casualties                          0
Speed_Limit                           153
Distance_to_Nearest_Hospital            0
Distance_to_Nearest_Police_Station      0
Visibility                              0
Road_Width                            157
Road_Surface_Friction_Coefficient       0
Vehicle_Speed                         177
Time_Taken_for_Emergency_Response     166
dtype: int64

In [ ]:
df.fillna({'Weather_Conditions' : df['Weather_Conditions'].mode()[0],
           'Type_of_Junction' : df['Type_of_Junction'].mode()[0],
           'Speed_Limit' : df['Speed_Limit'].mean(),
           'Road_Width' : df['Road_Width'].mean(),
           'Vehicle_Speed' : df['Vehicle_Speed'].mean(),
           'Time_Taken_for_Emergency_Response': df['Time_Taken_for_Emergency_Response'].mean()},
           inplace = True)

In [ ]:
df.isnull().sum()

ID                                    0
State                                 0
Date                                  0
Day_of_Week                           0
Time_of_Day                           0
Weather_Conditions                    0
Road_Conditions                       0
Light_Conditions                      0
Type_of_Road                          0
Type_of_Junction                      0
Type_of_Accident                      0
Vehicle_Type                          0
Driver_Age_Group                      0
Num_Vehicles_Involved                 0
Num_Casualties                        0
Speed_Limit                           0
Distance_to_Nearest_Hospital          0
Distance_to_Nearest_Police_Station    0
Visibility                            0
Road_Width                            0
Road_Surface_Friction_Coefficient     0
Vehicle_Speed                         0
Time_Taken_for_Emergency_Response     0
dtype: int64

Outliers Values

In [ ]:
def detect_outliers_iqr (df, columns):
    Q1 = df[columns].quantile(0.25)
    Q3 = df[columns].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = df[(df[columns] < lower) | (df[columns] > upper)]
    return outliers

outliers_speed = detect_outliers_iqr(df,'Vehicle_Speed')
print(len(outliers_speed))
outliers_limit = detect_outliers_iqr(df,'Speed_Limit')
print(len(outliers_limit))
outliers_emerg = detect_outliers_iqr(df,'Time_Taken_for_Emergency_Response')
print(len(outliers_emerg))
outliers_vic = detect_outliers_iqr(df,'Num_Vehicles_Involved')
print(len(outliers_vic))
outliers_casu = detect_outliers_iqr(df,'Num_Casualties')
print(len(outliers_casu))

0
0
0
0
0

In [ ]:
def remove_outliers_iqr (df, columns):
    Q1 = df[columns].quantile(0.25)
    Q3 = df[columns].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    return df[(df[columns] < lower) & (df[columns] > upper)]

# df = remove_outliers_iqr(df,'Vehicle_Speed')

Suring

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1610 entries, 0 to 1609
Data columns (total 23 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  1610 non-null   int64
 1   State                               1610 non-null   object
 2   Date                                1610 non-null   datetime64[ns]
 3   Day_of_Week                         1610 non-null   object
 4   Time_of_Day                         1610 non-null   datetime64[ns]
 5   Weather_Conditions                  1610 non-null   object
 6   Road_Conditions                     1610 non-null   object
 7   Light_Conditions                    1610 non-null   object
 8   Type_of_Road                        1610 non-null   object
 9   Type_of_Junction                    1610 non-null   object
 10  Type_of_Accident                    1610 non-null   object
 11  Vehicle_Type                        1610 non-null   object
 12  Driver_Age_Group                    1610 non-null   object
 13  Num_Vehicles_Involved               1610 non-null   int64
 14  Num_Casualties                      1610 non-null   int64
 15  Speed_Limit                         1610 non-null   float64
 16  Distance_to_Nearest_Hospital        1610 non-null   float64
 17  Distance_to_Nearest_Police_Station  1610 non-null   float64
 18  Visibility                          1610 non-null   float64
 19  Road_Width                          1610 non-null   float64
 20  Road_Surface_Friction_Coefficient   1610 non-null   float64
 21  Vehicle_Speed                       1610 non-null   float64
 22  Time_Taken_for_Emergency_Response   1610 non-null   float64
dtypes: datetime64[ns](2), float64(8), int64(3), object(10)
memory usage: 289.4+ KB

Transform File to Excel

In [ ]:
df.to_excel("formated_road_accident_data.xlsx", index = False)